### ISSUE TITLE
Reviewed by YuningXie

### ISSUE THREAD

**Issue by ynxie** [BrefCool/TwitterImgUtil#1]
The code is really comprehensive, taking lots of situation into consideration. There are comments on each function, which explain the input parameters and output results. And he write function to resize the images downloaded from the twitter account to make a more beautiful video. However, it's really hard for me to demo this program because he did not apply version that users can directly use. I think it need more instructions on how to successfully run the code. Overall, this is a perfect and comprehensive project.

**Comment by BrefCool** [comment]
Thanks to your advice. I have updated testShell.ipynb, you can use it as a demo.
